#数据库配置信息
#依赖去掉<scope>runtime</scope>否则驱动名称报红,驱动com.mysql.jdbc.Driver废弃
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wzh?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


#启动类也需要添加扫描Dao注解：@MapperScan("xxx")
mybatis:
  typeAliasesPackage: com.wzh.tools.spring.domain
  mapperLocations: classpath:mapper/*.xml


logging:
  level:
    com.wzh.tools.springboot : debug

----------------------------
#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


----------------------------
redis:
  dispenser: true
  mastername: mymaster
  redisaddr: 39.107.27.55:6379
  pool:
    maxTotal: 500
    maxIdle: 100
    minIdle: 20
    maxWaitMillis: 10000
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    numTestsPerEvictionRun: 10
    minEvictableIdleTimeMillis: 60000
----------------------------